# Generated by Django 4.2.7 on 2026-09-17 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_finalize_customer_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_code', models.CharField(max_length=50, unique=True, verbose_name='Distributor Code')),
                ('distributor_name', models.CharField(max_length=255, verbose_name='Distributor Name')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['city', 'distributor_name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='stock.distributor', verbose_name='Distributor'),
        ),
    ]
