# Generated by Django 5.1.1 on 2026-09-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_distributor_customer_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='customer',
            name='store_image',
            field=models.TextField(blank=True, null=True, verbose_name='Store Image'),
        ),
    ]
