# Generated by Django 5.1.1 on 2026-09-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_customer_phone_number_customer_store_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='channel',
            field=models.CharField(blank=True, choices=[('OPEN_MARKET', 'Open Market'), ('NG', 'NG Market'), ('SMALL_SUPERMARKET', 'Small Supermarket'), ('WHOLESALE', 'Wholesale')], max_length=50, null=True, verbose_name='Channel/Market'),
        ),
    ]
