databases:
  - name: price-pickup-db
    plan: free
    databaseName: price_pickup
    user: price_pickup

services:
  - type: web
    name: price-pickup-backend
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: price-pickup-db
          property: connectionString
