# Generated by Django 4.2.7 on 2025-05-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitorprice',
            name='gram_pack',
        ),
        migrations.RemoveField(
            model_name='competitorprice',
            name='gram_unit',
        ),
        migrations.RemoveField(
            model_name='competitorprice',
            name='kd_case_price',
        ),
        migrations.RemoveField(
            model_name='competitorprice',
            name='kd_price_gram',
        ),
        migrations.RemoveField(
            model_name='competitorprice',
            name='kd_unit_price',
        ),
        migrations.RemoveField(
            model_name='competitorprice',
            name='ng_pack_price',
        ),
        migrations.RemoveField(
            model_name='competitorprice',
            name='open_market_pack_price',
        ),
        migrations.RemoveField(
            model_name='competitorprice',
            name='pack_case',
        ),
        migrations.RemoveField(
            model_name='competitorprice',
            name='small_supermarket_pack_price',
        ),
        migrations.RemoveField(
            model_name='competitorprice',
            name='unit_pack',
        ),
        migrations.AddField(
            model_name='competitorprice',
            name='selling_price_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Selling Price (Unit)'),
        ),
        migrations.AddField(
            model_name='competitorprice',
            name='sku_description',
            field=models.TextField(blank=True, null=True, verbose_name='SKU Description'),
        ),
        migrations.AddField(
            model_name='competitorprice',
            name='sku_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SKU Name'),
        ),
    ]
