# Generated by Django 4.2.7 on 2025-05-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0002_remove_competitorprice_gram_pack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorprice',
            name='source',
            field=models.CharField(choices=[('CSV', 'Imported from CSV'), ('FORM', 'Created from form')], default='FORM', max_length=10, verbose_name='Data Source'),
        ),
    ]
