# Generated by Django 4.2.7 on 2026-09-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0002_alter_competitorprice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitorprice',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Brand'),
        ),
    ]
