# Generated by Django 4.2.7 on 2025-05-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0003_competitorprice_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorprice',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='competitorprice',
            name='is_unilever',
            field=models.BooleanField(default=False, verbose_name='Is Unilever Product'),
        ),
        migrations.AddField(
            model_name='competitorprice',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='competitorprice',
            name='market_type',
            field=models.CharField(choices=[('OPEN_MARKET', 'Open Market'), ('NG', 'NG Market'), ('SMALL_SUPERMARKET', 'Small Supermarket'), ('WHOLESALE', 'Wholesale')], max_length=50, verbose_name='Market Type'),
        ),
        migrations.AlterField(
            model_name='competitorprice',
            name='sku_size_category',
            field=models.CharField(choices=[('BULK PACK', 'BULK PACK'), ('MID PACK', 'MID PACK'), ('REGULAR PACK', 'REGULAR PACK'), ('SMALL PACK', 'SMALL PACK'), ('POWERS', 'POWERS')], max_length=255, verbose_name='SKU Size Category'),
        ),
    ]
