# Generated by Django 5.1.1 on 2026-09-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0003_alter_competitorprice_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorprice',
            name='units_per_case',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Units per Case'),
        ),
    ]
