# Generated by Django 4.2.7 on 2025-05-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0004_competitorprice_brand_competitorprice_is_unilever_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitorprice',
            name='market_type',
        ),
        migrations.RemoveField(
            model_name='competitorprice',
            name='selling_price_case',
        ),
        migrations.RemoveField(
            model_name='competitorprice',
            name='selling_price_unit',
        ),
        migrations.RemoveField(
            model_name='competitorprice',
            name='sku_description',
        ),
        migrations.RemoveField(
            model_name='competitorprice',
            name='sku_size_category',
        ),
        migrations.AddField(
            model_name='competitorprice',
            name='kd_case',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='KD Case'),
        ),
        migrations.AddField(
            model_name='competitorprice',
            name='kd_price_gram',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='KD Price/Gram'),
        ),
        migrations.AddField(
            model_name='competitorprice',
            name='kd_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='KD Unit'),
        ),
        migrations.AddField(
            model_name='competitorprice',
            name='ng_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='NG Price'),
        ),
        migrations.AddField(
            model_name='competitorprice',
            name='open_market_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Open Market Price'),
        ),
        migrations.AddField(
            model_name='competitorprice',
            name='sku_size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SKU Size'),
        ),
        migrations.AddField(
            model_name='competitorprice',
            name='small_supermarket_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Small Supermarket Price'),
        ),
        migrations.AddField(
            model_name='competitorprice',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Wholesale Price'),
        ),
        migrations.AlterField(
            model_name='competitorprice',
            name='sku_category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SKU Category'),
        ),
    ]
