# Generated by Django 4.2.7 on 2025-06-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0006_auto_20250603_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitorprice',
            name='sku_category',
            field=models.CharField(blank=True, choices=[('NUTRITION', 'NUTRITION'), ('ORAL CARE', 'ORAL CARE'), ('DEODORANT', 'DEODORANT'), ('SKIN CARE', 'SKIN CARE'), ('SALVORY', 'SALVORY')], max_length=255, null=True, verbose_name='SKU Category'),
        ),
        migrations.AlterField(
            model_name='competitorprice',
            name='sku_size',
            field=models.CharField(blank=True, choices=[('BULK PACK', 'BULK PACK'), ('MID PACK', 'MID PACK'), ('REGULAR PACK', 'REGULAR PACK'), ('SMALL PACK', 'SMALL PACK'), ('POWDERS', 'POWDERS')], max_length=255, null=True, verbose_name='SKU Size'),
        ),
    ]
